name: Run ping test
on: [push]

jobs:
  pytest:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up go 1.18
        uses: actions/setup-go@v2
        with:
          go-version: "1.18"
        id: go
      - name: Set up Python 3.10
        uses: actions/setup-python@v2
        with:
          python-version: "3.10"
      - name: setup module
        run: |
          git submodule init
          git submodule sync
          git submodule update
      - name: prepare
        run: |
          sudo ./ubuntu-22-dev/scripts/setup_bpf.sh
          make proto
          sudo make install
      - name: run unit test
        run: |
          cd test
          sudo ./test_srv6_ping.sh